#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST != "false" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

git clone https://${GH_TOKEN}@github.com/Compete-McGill/cp-website.git --branch gh-pages

gulp build 

cp -r img scss css vendor js index.html favicon.png cp-website/

cd cp-website

# push
git config user.email "president@compete-mcgill.ca"
git config user.name "Compete McGill Bot"
git add --all 
# force since in gitignore
git add -f vendor/* 
git commit --quiet -m "Travis #$TRAVIS_BUILD_NUMBER" 
git push -f --quiet origin gh-pages 
git tag "releases/1.$TRAVIS_BUILD_NUMBER"
git push -f --tags origin gh-pages
